### PR TITLE
adding forceWatch option to elm-webpack-loader

### PR DESCRIPTION
**Pull request by DougVonMoser**
Main.elm triggered out of the box, needed this forceWatch flag to get HMR working on App.elm

### CODE REVIEW

**Comment by simonh1000** [comment]
Could you describe more what did not work. I've been using this setup for years without problem. Although I did change the dev server yesterday I'm not sure that could have affected the line you propose to change

**Comment by DougVonMoser** [comment]
Sure thing, apologies. 
Main.elm is being required off of the webpack entry, so I assume webpack sees that just fine. Any changes to Main.elm trigger another webpack compilation. 
However, without the forceWatch option, that is the only .elm file that triggers a webpack compilation for me. Changes to App.elm does not get picked up and require a hard reload. 

Full disclosure I do not know what's going on under the hood, I just peeked at https://github.com/elm-community/elm-webpack-loader#forcewatch-default-false and that worked for me. Perhaps an issue first would have been more appropriate. 

macOS 10.12.6
Node 8.11.1

**Comment by simonh1000** [comment]
That's very strange. As you might imagine, the situation you describe is very, very common and I've never had any problem on Mac or Linux, and nor has it been raised by other users.

**Comment by DougVonMoser** [comment]
cool cool, thanks for giving it a thought. sweet repo btw. thanks!

**Comment by tritowntim** [comment]
Same issue here. This fix worked. Thanks @DougVonMoser!

macOS 10.13.5
node 9.11.1
npm 6.1.0

**Comment by simonh1000** [comment]
Ok. I'll have to double check this then 😊

**Comment by simonh1000** [comment]
Thanks - now I can confirm that on y mac I also need this too - so thanks for providing this.

**Pull request merged**
